---

ansible_host: host-4.keilarannanpalvelin.fi
ansible_user: jle
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"

influxdb_primary_username: admin
influxdb_primary_password: "{{ vault_influxdb_primary_password }}"
influxdb_primary_organization_name: home
influxdb_reader_username: grafana
influxdb_reader_password: "{{ vault_influxdb_reader_password }}"

grafana_admin_password: "{{ vault_grafana_admin_password }}"
